#!/bin/sh

# wan_failback
# Version 1.0.0
#
# Copyright (c) 2021 Ryan Adams
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.



# Set the primary_wan_if and backup_wan_if as appropriate below.
# Ensure "State Killing on Gateway Failure" 
# under System > Advanced > Miscellaneous is enabled.
# Use the Cron package to set this script to run periodically.
# Script excludes states related to DNS, DoT, ICMP, and DHCP from its
# checks. If you wish to exclude other traffic that may be expected on
# the backup WAN, see line 43 of this code.


primary_wan_if="em0"
backup_wan_if="ue0"


wan2_ipaddress=`ifconfig ${backup_wan} | grep 'inet ' | awk '{ print $2}' | cut -d'/' -f1`
default_gw=`netstat -rn | grep default | awk '{print $4}'`
if [ ${default_gw} != ${primary_wan_if} ]; then
  echo 'Primary WAN (' ${primary_wan_if} ')  is down; exiting'
  exit 0
fi
echo 'Primary WAN is up; checking for active states on Backup WAN (' ${backup_wan_if} ')'
backup_wan_states=`pfctl -i ${backup_wan_if} -ss |  grep -v -e ':853' -e ':53' -e 'icmp' -e ':67'`
echo ${backup_wan_states}
if [ -n "${backup_wan_states}" ]; then
echo 'Active states exist on Backup WAN; killing states on Backup WAN (' ${backup_wan_if} ')'
    /etc/rc.kill_states ${backup_wan_if} ${wan2_ipaddress}
else
  echo 'No active states exist on Backup WAN; exiting'
  exit 0
fi